USE MPMHC3

 CREATE TABLE MPMHC3SETTINGMESSAGEDETAIL ( 
 SETTINGID uniqueidentifier NULL,
 SETTINGDETAILID uniqueidentifier NULL,
 PARAMNAME varchar(100) NULL,
 URUTAN int NULL,
 CREATEBY varchar(25) NULL,
 CREATEDATE datetime NULL,
 MODIFBY varchar(25) NULL,
 MODIFDATE datetime NULL
);
