USE MPMHC3

 CREATE TABLE MPMHC3SURVEYPERTANYAAN ( 
 PERTANYAANID uniqueidentifier NULL,
 PERTANYAAN varchar(1000) NULL,
 TYPEJAWABAN int NULL,
 SURVEYID uniqueidentifier NULL,
 CREATEBY varchar(25) NULL,
 CREATEDATE datetime NULL,
 MODIFBY varchar(25) NULL,
 MODIFDATE datetime NULL
);
